require 'ostruct'
require 'markov'
require 'passive_record'
require 'graphviz'
require 'tty-table'

require 'versus/version'
require 'versus/configuration'

require 'versus/genealogy'
require 'versus/aristocracy'

require 'versus/model'
require 'versus/profession'
require 'versus/event'
require 'versus/event_participation'
require 'versus/person'
require 'versus/relationship'
require 'versus/town'
require 'versus/region'
require 'versus/continent'
require 'versus/world'
require 'versus/universe'
require 'versus/family_tree'
require 'versus/engine'
